SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM EVENT;
DELETE FROM EVENT_STATE;
DELETE FROM MEMBER;
DELETE FROM STATE_NAME;
DELETE FROM SUGGESTION;
DELETE FROM TASK_GROUP;
DELETE FROM AUTHORITIES;
DELETE FROM USER_AUTHORITIES;
DELETE FROM USER;
DELETE FROM VOTE;
DELETE FROM VOTE_STATE;
SET FOREIGN_KEY_CHECKS = 1;

